### PR TITLE
remove unnecessary ifs

### PR DESCRIPTION
**Pull request by maliberty**

### CODE REVIEW

**Comment by maliberty** [comment]
Would someone approve or comment?

**Comment by abdelrahmanhosny** [comment]
I think these were added because RePlAce had a tight integration and targets were added twice if OpenDB was build from an outside application. It would make sense to remove them now, but safer to double check with @jjcherry56 that this will not break OpenROAD build (because a target gets built twice)

**Comment by jjcherry56** [comment]
There is nothing in openroad itself that requires them and any tool that
tries to build them itself has a broken cmake file that needs to be fixed.
Replace uses a separate branch for the stand alone application to avoid
this issue.

**Comment by maliberty** [comment]
So can I get an approval?

**Pull request merged**
