### PR TITLE
remove tmg et al

### PR DESCRIPTION
**Pull request by jjcherry56**
remove all tmg structures from database. we don't have any use for them

### CODE REVIEW

**Comment by abdelrahmanhosny** [comment]
[log.txt](https://github.com/The-OpenROAD-Project/OpenDB/files/3839461/log.txt)

Attached is the log that breaks the CI pipeline.

**Comment by jjcherry56** [comment]
So I'm going to remove the test that checks the accessor that fails.
How do I run the tests locally? jenkins/test-tcl.sh doesn't work
because assumes the existence of a docker container. I couldn't find
a cwd that made tests/regression-tcl.sh happy either. Nothing in the
README says how to run the tests either.

CerezaBook> tests/regression-tcl.sh
Running tests ..
================
[1] Importing opendbtcl package
tests/regression-tcl.sh: line 7: ./OpenDB/build/src/swig/tcl/opendbtcl: No
such file or directory
CerezaBook> cd ..
CerezaBook> pwd
/Users/cherry/sta/openroad/src
CerezaBook> OpenDB/tests/regression-tcl.sh
Running tests ..
================
[1] Importing opendbtcl package
OpenDB/tests/regression-tcl.sh: line 7:
./OpenDB/build/src/swig/tcl/opendbtcl: No such file or directory

**Comment by jjcherry56** [comment]
Abdelrahman,

Can you help with this?

Tom

**Comment by abdelrahmanhosny** [comment]
```
CerezaBook> pwd
/Users/cherry/sta/openroad/src
CerezaBook> OpenDB/tests/regression-tcl.sh
Running tests ..
================
[1] Importing opendbtcl package
OpenDB/tests/regression-tcl.sh: line 7:
./OpenDB/build/src/swig/tcl/opendbtcl: No such file or directory
```
This is the correct directory and command to run the tests from. However, it cannot find `opendbtcl`. Does this build turn off `BUILD_TCL` option in the CMake? Or changes the destination of `opendbtcl`?

**Comment by jjcherry56** [comment]
It is turned on at the top:
BUILD_TCL:BOOL=ON

but somehow didn't happen as a submodule. I can cmake it inside the submodule.
I committed and pushed an update to the branch but I don't know how to wake this up to that fact. Do I close and resubmit?

**Comment by abdelrahmanhosny** [comment]
You don't need to re-submit. It already picked up the change, but failed at the next test. 

There is another instance of the function that we need to address in this [test file: line 33](https://github.com/The-OpenROAD-Project/OpenDB/blob/805e628a37243a6098b686275c961b442e84a5a0/tests/tcl/11-gcd_pdn_def_access_test.tcl#L33). I think if you remove it too, it should pass. These are the only two instances I can find for this function.

**Comment by jjcherry56** [comment]
Finally! Thanks for your help.

**Pull request merged**
