### PR TITLE
revised clang-format settings

### PR DESCRIPTION
**Pull request by maliberty**

### CODE REVIEW

**Comment by jjcherry56** [comment]
this should not be separated from reformatting the code. I depend on the existing format spec to modify the code

**Comment by maliberty** [comment]
Ok I'll leave it until after the demo.  That said the existing code is not formatted according to the existing .clang-format file.

**Comment by jjcherry56** [comment]
it kinda works better than my builtin indentation settings so it is useful

**Comment by maliberty** [comment]
Now that the demo is over I'd like to merge this branch.

**Pull request merged**
