### PR TITLE
Fix/suppress swig warnings

### PR DESCRIPTION
**Pull request by ahmed-agiza**
- Fixed/suppressed all SWIG warning messages
- Fixed more compiler warnings (currently, the debug build has no warnings on my local environment, still some warning in the release).
- Added TCL setups script to do any TCL preprocessing.
- The TCL shell now automatically has an initialized **$db** variable (i.e. no need for dbDatabase_create)
- The TCL shell now has read_lef, read_def, read_design, write_lef, write_def, export_db, and import_db, only exposed in the TCL shell binary so no conflicts with any top-level app.
- The -lrt link is now disabled by default unless -DLINK_RT=ON is specified.

### CODE REVIEW

**Comment by ahmed-agiza** [comment]
> Take a look at Cherry's recent changes. The build was broken unless compiled debug.

I already merged his commit into this branch, the rt now is not linked unless explicitly enabled, it is needed on some OS's #36.

**Comment by ahmed-agiza** [comment]
> Take a look at Cherry's recent changes. The build was broken unless compiled debug.

@tspyrou I already merged his commit into this branch, the rt now is not linked unless explicitly enabled, it is needed on some OS's #36.
Btw #45 breaks the regression tests in RELEASE mode (and hence this PR), we need to change the CI to build the release version too @abdelrahmanhosny?

**Comment by Colin-Holehouse** [comment]
I think the helpers can be handled a bit better - I think src/swig/tcl/helpers.tcl should be

```
R"=====(

namespace eval odb {
    variable db [dbDatabase_create]
    proc read_lef {lef_files} {
        variable db
        return [odb_read_lef $db $lef_files]
    }
    proc read_def {def_file} {
        variable db
        return [odb_read_def $db $def_file]
    }
    proc read_design {lef_files def_file} {
        variable db
        return [odb_read_design $db $lef_file $def_file]
    }
    proc write_lef {file_name} {
        variable db
        return [odb_write_lef [$db getLibs] $file_name]
    }
    proc write_def {file_name} {
        variable db
        return [odb_write_def [[$db getChip] getBlock] $file_name]
    }
    proc import_db {file_name} {
        variable db
        return [odb_import_db $db $file_name]
    }
    proc export_db {file_name} {
        variable db
        return [odb_export_db $db $file_name]
    }
    proc get_db {} {
        variable db
        return $db
    }
    namespace export *
    namespace ensemble create
}


)====="
```


The namespace ensemble command creates a command with the same name as the namespace, where the 1st argument is the name of the function in the namespace to call, the remaining arguments will then be as usual, so the commands would be:

```
odb read_lef library.lef
odb read_def test.def
... some more db commands here ...
odb write_def output.def
```
The variable db stays in the odb namespace, unless the user gets it with the odb get_db command

This also allay's Tom concerns over possible namespace clashes.

**Comment by Colin-Holehouse** [comment]
Most of the time we will be dealing with the block object that gets loaded into the db, so it would be nice to have a helper function for that as well:

```
namespace eval odb {
   ....
    proc get_block {} {
        variable db
        return [[$db getChip] getBlock]
    }
    ....
}
```

**Comment by ahmed-agiza** [comment]
@tspyrou yes as I mentioned I made them available through opendb TCL binary only, they will not conflict with the top level. But you may wait until I incorporate @Colin-Holehouse suggestions unless you disagree with any of it. I will ping you again when I add them.

**Comment by ahmed-agiza** [comment]
Closed for further edits.

**Pull request closed without merging**
