### PR TITLE
Add Doxygen documentation support.

### PR DESCRIPTION
**Pull request by trcwm**
Added Doxygen support so we get some documentation in the form of class diagrams and an easily navigatable class/function tree.

### CODE REVIEW

**Comment by trcwm** [comment]
Anybody?

**Comment by rovinski** [comment]
@maliberty

**Comment by maliberty** [comment]
I would prefer to see cmake used for this so the generated result goes in the build area (see https://cmake.org/cmake/help/latest/module/FindDoxygen.html).

**Comment by maliberty** [comment]
I've added a 'docs' target using cmake.  It will show up in our next merge to github.  It amounts to:

find_package(Doxygen)

if (DOXYGEN_FOUND)
  set(DOXYGEN_EXTRACT_STATIC YES)
  set(DOXYGEN_REFERENCED_BY_RELATION YES)
  set(DOXYGEN_REFERENCES_RELATION YES)

  doxygen_add_docs(docs include)
endif()

I don't think src should be included as it isn't part of the public API.

**Pull request closed without merging**
